########################
## Main class options ##
########################
# Increases local clock's value
timeZoneOffset=2
defaultChangeID=113430779-118908795-111504117-128668306-120161309

##############################
## WorkerController options ##
##############################
workerLimit=5

####################
## Worker options ##
####################
downloadChunkSize=128
defaultAPIURL=http://www.pathofexile.com/api/public-stash-tabs?id=
# Delay in milliseconds (***MUST be over 500)
downloadDelay=800

##############################
## PricerController options ##
##############################
# One cycle's length in seconds
PricerControllerSleepCycle=60
# How many cycles until JSON is compiled and written to file
DataEntryCycleLimit=5

#########################
## DataEntry's options ##
#########################
baseDataSize=100
hourlyDataSize=60
duplicatesSize=60